version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: grocery-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: hanumant
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - ":3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: grocery-api
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hanumant?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
    ports:
      - :80

volumes:
  mysql_data:
